version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t uzzal2k5/django-docker:$TAG .
            docker login -u uzzal2k5 -p shafiq2k5
            docker push uzzal2k5/django-docker:$TAG