---
kind: PersistentVolume
apiVersion: v1
metadata:
   name: content-volume
   labels:
      type: local
spec:
   storageClassName: manual
   capacity:
      storage: 10G
   accessModes:
      - ReadWriteOnce
   hostPath:
      path: "/var/django-container"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: content-volume-claim
spec:
   storageClassName: manual
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 3Gi