---
kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  labels:
    app: postgresdb
spec:
  selector:
    name: postgres-data
    app: postgres-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres-docker
  labels:
    name: django-web
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-data
  template:
    metadata:
      labels:
        name: postgres-data
        app: postgres-db
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
             - name: postgres-storage
               mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
             claimName: postgres-volume-claim